version: '3.8'

services:
  mediafusion:
    image: mhdzumair/mediafusion:latest
    container_name: mediafusion
    restart: unless-stopped
    depends_on:
      mongodb:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      # Core Configuration
      ADDON_NAME: "${ADDON_NAME:-MediaFusion}"
      HOST_URL: "${HOST_URL}"
      SECRET_KEY: "${SECRET_KEY}"
      API_PASSWORD: "${API_PASSWORD}"
      CONTACT_EMAIL: "${CONTACT_EMAIL:-admin@mediafusion.local}"
      DESCRIPTION: "${DESCRIPTION:-Advanced Stremio addon with torrent streaming, debrid integration, and comprehensive scraping from multiple sources including Prowlarr, Jackett, and public trackers.}"
      TZ: "${TZ:-UTC}"
      LOGGING_LEVEL: "${LOGGING_LEVEL:-INFO}"
      IS_PUBLIC_INSTANCE: "${IS_PUBLIC_INSTANCE:-false}"
      
      # Database Configuration
      MONGO_URI: "${MONGO_URI:-mongodb://mongodb:27017/mediafusion}"
      DB_MAX_CONNECTIONS: "${DB_MAX_CONNECTIONS:-50}"
      REDIS_URL: "${REDIS_URL:-redis://redis:6379}"
      REDIS_MAX_CONNECTIONS: "${REDIS_MAX_CONNECTIONS:-100}"
      REQUESTS_PROXY_URL: "${REQUESTS_PROXY_URL:-}"
      
      # External Services
      TMDB_API_KEY: "${TMDB_API_KEY:-}"
      
      # Prowlarr Configuration
      IS_SCRAP_FROM_PROWLARR: "${IS_SCRAP_FROM_PROWLARR:-false}"
      PROWLARR_URL: "${PROWLARR_URL:-}"
      PROWLARR_API_KEY: "${PROWLARR_API_KEY:-}"
      PROWLARR_LIVE_TITLE_SEARCH: "${PROWLARR_LIVE_TITLE_SEARCH:-true}"
      PROWLARR_BACKGROUND_TITLE_SEARCH: "${PROWLARR_BACKGROUND_TITLE_SEARCH:-true}"
      PROWLARR_SEARCH_QUERY_TIMEOUT: "${PROWLARR_SEARCH_QUERY_TIMEOUT:-30}"
      PROWLARR_SEARCH_INTERVAL_HOUR: "${PROWLARR_SEARCH_INTERVAL_HOUR:-72}"
      PROWLARR_IMMEDIATE_MAX_PROCESS: "${PROWLARR_IMMEDIATE_MAX_PROCESS:-10}"
      PROWLARR_IMMEDIATE_MAX_PROCESS_TIME: "${PROWLARR_IMMEDIATE_MAX_PROCESS_TIME:-15}"
      PROWLARR_FEED_SCRAPE_INTERVAL_HOUR: "${PROWLARR_FEED_SCRAPE_INTERVAL_HOUR:-3}"
      
      # Torrentio Configuration
      IS_SCRAP_FROM_TORRENTIO: "${IS_SCRAP_FROM_TORRENTIO:-false}"
      TORRENTIO_URL: "${TORRENTIO_URL:-https://torrentio.strem.fun}"
      TORRENTIO_SEARCH_INTERVAL_DAYS: "${TORRENTIO_SEARCH_INTERVAL_DAYS:-3}"
      
      # MediaFusion Scraping Configuration
      IS_SCRAP_FROM_MEDIAFUSION: "${IS_SCRAP_FROM_MEDIAFUSION:-false}"
      MEDIAFUSION_URL: "${MEDIAFUSION_URL:-https://mediafusion.elfhosted.com}"
      MEDIAFUSION_SEARCH_INTERVAL_DAYS: "${MEDIAFUSION_SEARCH_INTERVAL_DAYS:-3}"
      SYNC_DEBRID_CACHE_STREAMS: "${SYNC_DEBRID_CACHE_STREAMS:-true}"
      
      # Zilean Configuration
      IS_SCRAP_FROM_ZILEAN: "${IS_SCRAP_FROM_ZILEAN:-false}"
      ZILEAN_URL: "${ZILEAN_URL:-https://zilean.elfhosted.com}"
      ZILEAN_SEARCH_INTERVAL_HOUR: "${ZILEAN_SEARCH_INTERVAL_HOUR:-24}"
      
      # BT4G Configuration
      IS_SCRAP_FROM_BT4G: "${IS_SCRAP_FROM_BT4G:-true}"
      BT4G_URL: "${BT4G_URL:-https://bt4gprx.com}"
      BT4G_SEARCH_INTERVAL_HOUR: "${BT4G_SEARCH_INTERVAL_HOUR:-72}"
      BT4G_SEARCH_TIMEOUT: "${BT4G_SEARCH_TIMEOUT:-10}"
      BT4G_IMMEDIATE_MAX_PROCESS: "${BT4G_IMMEDIATE_MAX_PROCESS:-15}"
      BT4G_IMMEDIATE_MAX_PROCESS_TIME: "${BT4G_IMMEDIATE_MAX_PROCESS_TIME:-15}"
      
      # Jackett Configuration
      IS_SCRAP_FROM_JACKETT: "${IS_SCRAP_FROM_JACKETT:-false}"
      JACKETT_URL: "${JACKETT_URL:-}"
      JACKETT_API_KEY: "${JACKETT_API_KEY:-}"
      JACKETT_SEARCH_INTERVAL_HOUR: "${JACKETT_SEARCH_INTERVAL_HOUR:-72}"
      JACKETT_SEARCH_QUERY_TIMEOUT: "${JACKETT_SEARCH_QUERY_TIMEOUT:-30}"
      JACKETT_IMMEDIATE_MAX_PROCESS: "${JACKETT_IMMEDIATE_MAX_PROCESS:-10}"
      JACKETT_IMMEDIATE_MAX_PROCESS_TIME: "${JACKETT_IMMEDIATE_MAX_PROCESS_TIME:-15}"
      JACKETT_LIVE_TITLE_SEARCH: "${JACKETT_LIVE_TITLE_SEARCH:-true}"
      JACKETT_BACKGROUND_TITLE_SEARCH: "${JACKETT_BACKGROUND_TITLE_SEARCH:-true}"
      JACKETT_FEED_SCRAPE_INTERVAL_HOUR: "${JACKETT_FEED_SCRAPE_INTERVAL_HOUR:-3}"
      
      # Provider Configuration
      DISABLED_PROVIDERS: "${DISABLED_PROVIDERS:-[]}"
      
      # Premium Services Configuration
      PREMIUMIZE_OAUTH_CLIENT_ID: "${PREMIUMIZE_OAUTH_CLIENT_ID:-}"
      PREMIUMIZE_OAUTH_CLIENT_SECRET: "${PREMIUMIZE_OAUTH_CLIENT_SECRET:-}"
      
      # Application Configuration
      ENABLE_RATE_LIMIT: "${ENABLE_RATE_LIMIT:-false}"
      VALIDATE_M3U8_URLS_LIVENESS: "${VALIDATE_M3U8_URLS_LIVENESS:-true}"
      STORE_STREMTHRU_MAGNET_CACHE: "${STORE_STREMTHRU_MAGNET_CACHE:-false}"
      IS_SCRAP_FROM_YTS: "${IS_SCRAP_FROM_YTS:-true}"
      SCRAPE_WITH_AKA_TITLES: "${SCRAPE_WITH_AKA_TITLES:-true}"
      ENABLE_FETCHING_TORRENT_METADATA_FROM_P2P: "${ENABLE_FETCHING_TORRENT_METADATA_FROM_P2P:-true}"
      
      # Content Filtering
      ADULT_CONTENT_FILTER_IN_TORRENT_TITLE: "${ADULT_CONTENT_FILTER_IN_TORRENT_TITLE:-true}"
      ADULT_CONTENT_REGEX_KEYWORDS: "${ADULT_CONTENT_REGEX_KEYWORDS:-}"
      
      # Performance Configuration
      META_CACHE_TTL: "${META_CACHE_TTL:-1800}"
      WORKER_MAX_TASKS_PER_CHILD: "${WORKER_MAX_TASKS_PER_CHILD:-20}"
      
      # Background Tasks Configuration
      BACKGROUND_SEARCH_INTERVAL_HOURS: "${BACKGROUND_SEARCH_INTERVAL_HOURS:-72}"
      BACKGROUND_SEARCH_CRONTAB: "${BACKGROUND_SEARCH_CRONTAB:-*/5 * * * *}"
      DISABLE_ALL_SCHEDULER: "${DISABLE_ALL_SCHEDULER:-false}"
      
      # Metadata Configuration
      METADATA_PRIMARY_SOURCE: "${METADATA_PRIMARY_SOURCE:-imdb}"
      MIN_SCRAPING_VIDEO_SIZE: "${MIN_SCRAPING_VIDEO_SIZE:-26214400}"
      
      # Notification Configuration
      TELEGRAM_BOT_TOKEN: "${TELEGRAM_BOT_TOKEN:-}"
      TELEGRAM_CHAT_ID: "${TELEGRAM_CHAT_ID:-}"
      
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 20m
    volumes:
      - ${APP_DATA_DIR}/mediafusion:/app/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - tipi_main_network
    labels:
      # Traefik configuration
      traefik.enable: "true"
      traefik.http.services.mediafusion.loadbalancer.server.port: "8000"
      
      # HTTP to HTTPS redirect middleware
      traefik.http.middlewares.mediafusion-redirect.redirectscheme.scheme: "https"
      
      # External domain HTTP (redirect to HTTPS)
      traefik.http.routers.mediafusion-insecure.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.mediafusion-insecure.entrypoints: "web"
      traefik.http.routers.mediafusion-insecure.service: "mediafusion"
      traefik.http.routers.mediafusion-insecure.middlewares: "mediafusion-redirect"
      
      # External domain HTTPS
      traefik.http.routers.mediafusion.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.mediafusion.entrypoints: "websecure"
      traefik.http.routers.mediafusion.service: "mediafusion"
      traefik.http.routers.mediafusion.tls.certresolver: "myresolver"
      
      # Local domain HTTP (redirect to HTTPS)
      traefik.http.routers.mediafusion-local-insecure.rule: "Host(`mediafusion.${LOCAL_DOMAIN}`)"
      traefik.http.routers.mediafusion-local-insecure.entrypoints: "web"
      traefik.http.routers.mediafusion-local-insecure.service: "mediafusion"
      traefik.http.routers.mediafusion-local-insecure.middlewares: "mediafusion-redirect"
      
      # Local domain HTTPS
      traefik.http.routers.mediafusion-local.rule: "Host(`mediafusion.${LOCAL_DOMAIN}`)"
      traefik.http.routers.mediafusion-local.entrypoints: "websecure"
      traefik.http.routers.mediafusion-local.service: "mediafusion"
      traefik.http.routers.mediafusion-local.tls: "true"
      
      # Runtipi management label
      runtipi.managed: "true"

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: mediafusion
    volumes:
      - ${APP_DATA_DIR}/mongodb:/data/db
    command: ["mongod", "--bind_ip_all"]
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/redis:/data
    command: ["redis-server", "--appendonly", "yes", "--save", "60", "1"]
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"

networks:
  tipi_main_network:
    external: true
