version: "3.7"

services:
  czstreams:
    image: node:23-alpine
    container_name: czstreams
    restart: unless-stopped
    working_dir: /app
    
    volumes:
      - ${APP_DATA_DIR}/data:/app
      - ${APP_DATA_DIR}/node_modules:/app/node_modules
    
    ports:
      - ${APP_PORT}:52932
    
    environment:
      - NODE_ENV=production
      - PORT=52932
    
    command: >
      sh -c "
      npm install &&
      npm start
      "
    
    networks:
      - tipi_main_network
    
    labels:
      # Main service configuration
      traefik.enable: true
      traefik.http.middlewares.czstreams-web-redirect.redirectscheme.scheme: https
      traefik.http.services.czstreams.loadbalancer.server.port: 52932
      
      # Web (insecure HTTP)
      traefik.http.routers.czstreams-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.czstreams-insecure.entrypoints: web
      traefik.http.routers.czstreams-insecure.service: czstreams
      traefik.http.routers.czstreams-insecure.middlewares: czstreams-web-redirect
      
      # Websecure (HTTPS with public domain)
      traefik.http.routers.czstreams.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.czstreams.entrypoints: websecure
      traefik.http.routers.czstreams.service: czstreams
      traefik.http.routers.czstreams.tls.certresolver: myresolver
      
      # Local domain (insecure HTTP)
      traefik.http.routers.czstreams-local-insecure.rule: Host(`czstreams.${LOCAL_DOMAIN}`)
      traefik.http.routers.czstreams-local-insecure.entrypoints: web
      traefik.http.routers.czstreams-local-insecure.service: czstreams
      traefik.http.routers.czstreams-local-insecure.middlewares: czstreams-web-redirect
      
      # Local domain (secure HTTPS)
      traefik.http.routers.czstreams-local.rule: Host(`czstreams.${LOCAL_DOMAIN}`)
      traefik.http.routers.czstreams-local.entrypoints: websecure
      traefik.http.routers.czstreams-local.service: czstreams
      traefik.http.routers.czstreams-local.tls: true
      
      # Runtipi management label
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true