version: '3.7'

services:
  comet:
    image: g0ldyy/comet:latest
    container_name: comet
    restart: unless-stopped
    environment:
      # ==============================
      # Stremio Addon Configuration
      # ==============================
      ADDON_ID: "${ADDON_ID-stremio.comet.fast}"
      ADDON_NAME: "${ADDON_NAME-Comet}"

      # ==============================
      # FastAPI Server Configuration
      # ==============================
      FASTAPI_HOST: "${FASTAPI_HOST-0.0.0.0}"
      FASTAPI_PORT: "${FASTAPI_PORT-8000}"
      FASTAPI_WORKERS: "${FASTAPI_WORKERS-1}"
      USE_GUNICORN: "${USE_GUNICORN-True}"

      # ==============================
      # Dashboard Settings
      # ==============================
      ADMIN_DASHBOARD_PASSWORD: "${ADMIN_DASHBOARD_PASSWORD}"
      PUBLIC_METRICS_API: "${PUBLIC_METRICS_API-False}"

      # ==============================
      # Database Configuration
      # ==============================
      DATABASE_TYPE: "${DATABASE_TYPE-sqlite}"
      DATABASE_URL: "${DATABASE_URL-}"
      DATABASE_PATH: "${DATABASE_PATH-data/comet.db}"
      DATABASE_BATCH_SIZE: "${DATABASE_BATCH_SIZE-20000}"

      # ==============================
      # Cache Settings (Seconds)
      # ==============================
      METADATA_CACHE_TTL: "${METADATA_CACHE_TTL-2592000}"
      TORRENT_CACHE_TTL: "${TORRENT_CACHE_TTL-1296000}"
      DEBRID_CACHE_TTL: "${DEBRID_CACHE_TTL-86400}"
      SCRAPE_LOCK_TTL: "${SCRAPE_LOCK_TTL-300}"
      SCRAPE_WAIT_TIMEOUT: "${SCRAPE_WAIT_TIMEOUT-30}"

      # ==============================
      # Background Scraper Settings
      # ==============================
      BACKGROUND_SCRAPER_ENABLED: "${BACKGROUND_SCRAPER_ENABLED-False}"
      BACKGROUND_SCRAPER_CONCURRENT_WORKERS: "${BACKGROUND_SCRAPER_CONCURRENT_WORKERS-1}"
      BACKGROUND_SCRAPER_INTERVAL: "${BACKGROUND_SCRAPER_INTERVAL-3600}"
      BACKGROUND_SCRAPER_MAX_MOVIES_PER_RUN: "${BACKGROUND_SCRAPER_MAX_MOVIES_PER_RUN-100}"
      BACKGROUND_SCRAPER_MAX_SERIES_PER_RUN: "${BACKGROUND_SCRAPER_MAX_SERIES_PER_RUN-100}"

      # ==============================
      # Debrid Proxy Configuration
      # ==============================
      DEBRID_PROXY_URL: "${DEBRID_PROXY_URL-}"

      # ==============================
      # Indexer Manager Settings
      # ==============================
      INDEXER_MANAGER_TYPE: "${INDEXER_MANAGER_TYPE-none}"
      INDEXER_MANAGER_URL: "${INDEXER_MANAGER_URL-}"
      INDEXER_MANAGER_API_KEY: "${INDEXER_MANAGER_API_KEY-}"
      INDEXER_MANAGER_MODE: "${INDEXER_MANAGER_MODE-both}"
      INDEXER_MANAGER_TIMEOUT: "${INDEXER_MANAGER_TIMEOUT-60}"
      INDEXER_MANAGER_INDEXERS: "${INDEXER_MANAGER_INDEXERS-[]}"

      # ==============================
      # Torrent Settings
      # ==============================
      GET_TORRENT_TIMEOUT: "${GET_TORRENT_TIMEOUT-5}"
      DOWNLOAD_TORRENT_FILES: "${DOWNLOAD_TORRENT_FILES-False}"

      # ==============================
      # Scraping Configuration
      # ==============================
      SCRAPE_COMET: "${SCRAPE_COMET-False}"
      COMET_URL: "${COMET_URL-https://comet.elfhosted.com}"

      SCRAPE_NYAA: "${SCRAPE_NYAA-False}"
      NYAA_ANIME_ONLY: "${NYAA_ANIME_ONLY-True}"
      NYAA_MAX_CONCURRENT_PAGES: "${NYAA_MAX_CONCURRENT_PAGES-5}"

      SCRAPE_ZILEAN: "${SCRAPE_ZILEAN-False}"
      ZILEAN_URL: "${ZILEAN_URL-https://zilean.elfhosted.com}"

      SCRAPE_STREMTHRU: "${SCRAPE_STREMTHRU-False}"
      STREMTHRU_SCRAPE_URL: "${STREMTHRU_SCRAPE_URL-https://stremthru.13377001.xyz}"

      SCRAPE_TORRENTIO: "${SCRAPE_TORRENTIO-False}"
      TORRENTIO_URL: "${TORRENTIO_URL-https://torrentio.strem.fun}"

      SCRAPE_MEDIAFUSION: "${SCRAPE_MEDIAFUSION-False}"
      MEDIAFUSION_URL: "${MEDIAFUSION_URL-https://mediafusion.elfhosted.com}"
      MEDIAFUSION_API_PASSWORD: "${MEDIAFUSION_API_PASSWORD-}"
      MEDIAFUSION_LIVE_SEARCH: "${MEDIAFUSION_LIVE_SEARCH-True}"

      SCRAPE_AIOSTREAMS: "${SCRAPE_AIOSTREAMS-False}"
      AIOSTREAMS_URL: "${AIOSTREAMS_URL-}"
      AIOSTREAMS_USER_UUID_AND_PASSWORD: "${AIOSTREAMS_USER_UUID_AND_PASSWORD-}"

      SCRAPE_JACKETTIO: "${SCRAPE_JACKETTIO-False}"
      JACKETTIO_URL: "${JACKETTIO_URL-}"

      SCRAPE_DEBRIDIO: "${SCRAPE_DEBRIDIO-False}"
      DEBRIDIO_API_KEY: "${DEBRIDIO_API_KEY-}"

      SCRAPE_TORBOX: "${SCRAPE_TORBOX-False}"
      TORBOX_API_KEY: "${TORBOX_API_KEY-}"

      # ==============================
      # Debrid Stream Proxy Settings
      # ==============================
      PROXY_DEBRID_STREAM: "${PROXY_DEBRID_STREAM-False}"
      PROXY_DEBRID_STREAM_PASSWORD: "${PROXY_DEBRID_STREAM_PASSWORD-}"
      PROXY_DEBRID_STREAM_MAX_CONNECTIONS: "${PROXY_DEBRID_STREAM_MAX_CONNECTIONS--1}"
      PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE: "${PROXY_DEBRID_STREAM_DEBRID_DEFAULT_SERVICE-realdebrid}"
      PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY: "${PROXY_DEBRID_STREAM_DEBRID_DEFAULT_APIKEY-}"

      # ==============================
      # Content Filtering
      # ==============================
      REMOVE_ADULT_CONTENT: "${REMOVE_ADULT_CONTENT-False}"

      # ==============================
      # UI Customization
      # ==============================
      CUSTOM_HEADER_HTML: "${CUSTOM_HEADER_HTML-}"

      # ==============================
      # StremThru Integration
      # ==============================
      STREMTHRU_URL: "${STREMTHRU_URL-https://stremthru.13377001.xyz}"

    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8000/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 30s
    volumes:
      - ${APP_DATA_DIR}/comet:/data
    networks:
      - tipi_main_network
    labels:
      traefik.enable: "true"

      # Redirect HTTP → HTTPS
      traefik.http.middlewares.comet-redirect.redirectscheme.scheme: https

      # Internal port
      traefik.http.services.comet.loadbalancer.server.port: "8000"

      # HTTP router (insecure)
      traefik.http.routers.comet-insecure.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.comet-insecure.entrypoints: "web"
      traefik.http.routers.comet-insecure.service: "comet"
      traefik.http.routers.comet-insecure.middlewares: "comet-redirect"

      # HTTPS router (secure)
      traefik.http.routers.comet.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.comet.entrypoints: "websecure"
      traefik.http.routers.comet.service: "comet"
      traefik.http.routers.comet.tls.certresolver: "myresolver"

      # Local HTTP (insecure)
      traefik.http.routers.comet-local-insecure.rule: "Host(`comet.${LOCAL_DOMAIN}`)"
      traefik.http.routers.comet-local-insecure.entrypoints: "web"
      traefik.http.routers.comet-local-insecure.service: "comet"
      traefik.http.routers.comet-local-insecure.middlewares: "comet-redirect"

      # Local HTTPS (secure)
      traefik.http.routers.comet-local.rule: "Host(`comet.${LOCAL_DOMAIN}`)"
      traefik.http.routers.comet-local.entrypoints: "websecure"
      traefik.http.routers.comet-local.service: "comet"
      traefik.http.routers.comet-local.tls: "true"

      # Managed by Runtipi
      runtipi.managed: "true"

networks:
  tipi_main_network:
    external: true
