version: '3.8'
services:
  dockcheck:
    image: alpine:latest
    container_name: dockcheck
    cap_add:
      - NET_ADMIN
    command: >-
      sh -c "apk add --no-cache bash jq curl && \
      curl -L https://github.com/regclient/regclient/releases/latest/download/regctl-linux-amd64 -o /usr/local/bin/regctl && \
      chmod +x /usr/local/bin/regctl && \
      curl -L https://raw.githubusercontent.com/mag37/dockcheck/main/dockcheck.sh \
      -o /usr/local/bin/dockcheck.sh && \
      chmod +x /usr/local/bin/dockcheck.sh && \
      exec dockcheck.sh $${DOCKCHECK_FLAGS}"
    environment:
      AUTO_MODE: "${AUTO_MODE-false}"
      MAX_ASYNC: "${MAX_ASYNC-1}"
      DAYS_OLD: "${DAYS_OLD-0}"
      EXCLUDE_CONTAINERS: "${EXCLUDE_CONTAINERS-}"
      ONLY_LABEL: "${ONLY_LABEL-}"
      AUTO_PRUNE: "${AUTO_PRUNE-false}"
      EXTRA_FLAGS: "${EXTRA_FLAGS-}"
      TRAEFIK_HOSTS: "${TRAEFIK_HOSTS-}"
      DOCKCHECK_FLAGS: |
        $${AUTO_MODE:+-a} $${MAX_ASYNC:+-x $${MAX_ASYNC}} $${DAYS_OLD:+-d $${DAYS_OLD}} $${EXCLUDE_CONTAINERS:+-e $${EXCLUDE_CONTAINERS}} $${ONLY_LABEL:+-l} $${AUTO_PRUNE:+-p} $${EXTRA_FLAGS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data:/data
    networks:
      - tipi_main_network
    ports:
      - ${APP_PORT}:8080
    restart: unless-stopped
    labels:
      traefik.enable: true
      traefik.http.routers.dockcheck.rule: "Host(${TRAEFIK_HOSTS})"
      traefik.http.routers.dockcheck.entrypoints: websecure
      traefik.http.routers.dockcheck.tls.certresolver: myresolver
      traefik.http.services.dockcheck.loadbalancer.server.port: "8080"
      runtipi.managed: true
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "3"

networks:
  tipi_main_network:
    external: true
