version: "3.7"

services:
  stremthru:
    container_name: stremthru
    image: muniftanjim/stremthru:latest
    environment:
      - STREMTHRU_BASE_URL=${STREMTHRU_BASE_URL}
      - STREMTHRU_PORT=${STREMTHRU_PORT:-8080}
      - STREMTHRU_LOG_LEVEL=${STREMTHRU_LOG_LEVEL:-INFO}
      - STREMTHRU_LOG_FORMAT=${STREMTHRU_LOG_FORMAT:-json}
      - STREMTHRU_DATA_DIR=${STREMTHRU_DATA_DIR:-/app/data}
      - STREMTHRU_HTTP_PROXY=${STREMTHRU_HTTP_PROXY}
      - STREMTHRU_TUNNEL=${STREMTHRU_TUNNEL}
      - STREMTHRU_PROXY_AUTH=${STREMTHRU_PROXY_AUTH}
      - STREMTHRU_AUTH_ADMIN=${STREMTHRU_AUTH_ADMIN}
      - STREMTHRU_STORE_AUTH=${STREMTHRU_STORE_AUTH}
      - STREMTHRU_STORE_TUNNEL=${STREMTHRU_STORE_TUNNEL}
      - STREMTHRU_STORE_CONTENT_PROXY=${STREMTHRU_STORE_CONTENT_PROXY}
      - STREMTHRU_CONTENT_PROXY_CONNECTION_LIMIT=${STREMTHRU_CONTENT_PROXY_CONNECTION_LIMIT}
      - STREMTHRU_STORE_CONTENT_CACHED_STALE_TIME=${STREMTHRU_STORE_CONTENT_CACHED_STALE_TIME}
      - STREMTHRU_PEER_URI=${STREMTHRU_PEER_URI}
      - STREMTHRU_REDIS_URI=${STREMTHRU_REDIS_URI}
      - STREMTHRU_DATABASE_URI=${STREMTHRU_DATABASE_URI:-sqlite://./data/stremthru.db}
      - STREMTHRU_STREMIO_ADDON=${STREMTHRU_STREMIO_ADDON}
      - STREMTHRU_INTEGRATION_TRAKT_CLIENT_ID=${STREMTHRU_INTEGRATION_TRAKT_CLIENT_ID}
      - STREMTHRU_INTEGRATION_TRAKT_CLIENT_SECRET=${STREMTHRU_INTEGRATION_TRAKT_CLIENT_SECRET}
      - STREMTHRU_FEATURE=${STREMTHRU_FEATURE}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/stremthru:/app/data
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.stremthru-web-redirect.redirectscheme.scheme: https
      traefik.http.services.stremthru.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.stremthru-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stremthru-insecure.entrypoints: web
      traefik.http.routers.stremthru-insecure.service: stremthru
      traefik.http.routers.stremthru-insecure.middlewares: stremthru-web-redirect
      # Websecure
      traefik.http.routers.stremthru.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stremthru.entrypoints: websecure
      traefik.http.routers.stremthru.service: stremthru
      traefik.http.routers.stremthru.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.stremthru-local-insecure.rule: Host(`stremthru.${LOCAL_DOMAIN}`)
      traefik.http.routers.stremthru-local-insecure.entrypoints: web
      traefik.http.routers.stremthru-local-insecure.service: stremthru
      traefik.http.routers.stremthru-local-insecure.middlewares: stremthru-web-redirect
      # Local domain secure
      traefik.http.routers.stremthru-local.rule: Host(`stremthru.${LOCAL_DOMAIN}`)
      traefik.http.routers.stremthru-local.entrypoints: websecure
      traefik.http.routers.stremthru-local.service: stremthru
      traefik.http.routers.stremthru-local.tls: true
      runtipi.managed: true

  redis:
    container_name: stremthru-redis
    image: redis:7-alpine
    ports:
      - "8089:6379"
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    restart: unless-stopped
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

  postgres:
    container_name: stremthru-postgres
    image: postgres:16.6-alpine
    ports:
      - "8088:5432"
    environment:
      - POSTGRES_DB=stremthru
      - POSTGRES_USER=stremthru
      - POSTGRES_PASSWORD=stremthru
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/postgres:/var/lib/postgresql/data
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true
