version: '3.8'

services:
  stremthru:
    container_name: stremthru
    image: muniftanjim/stremthru:latest
    ports:
      - ${APP_PORT}:8080
    environment:
      - STREMTHRU_HTTP_PROXY=${STREMTHRU_HTTP_PROXY}
      - STREMTHRU_TUNNEL=${STREMTHRU_TUNNEL}
      - STREMTHRU_PROXY_AUTH=${STREMTHRU_PROXY_AUTH}
      - STREMTHRU_STORE_AUTH=${STREMTHRU_STORE_AUTH}
      - STREMTHRU_PEER_URI=${STREMTHRU_PEER_URI}
      - STREMTHRU_REDIS_URI=${STREMTHRU_REDIS_URI}
      - STREMTHRU_DATABASE_URI=${STREMTHRU_DATABASE_URI:-sqlite://./data/stremthru.db}
      - STREMTHRU_STREMIO_ADDON=${STREMTHRU_STREMIO_ADDON}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/stremthru:/app/data
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.stremthru-web-redirect.redirectscheme.scheme: https
      traefik.http.services.stremthru.loadbalancer.server.port: 8080
      # Web
      traefik.http.routers.stremthru-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stremthru-insecure.entrypoints: web
      traefik.http.routers.stremthru-insecure.service: stremthru
      traefik.http.routers.stremthru-insecure.middlewares: stremthru-web-redirect
      # Websecure
      traefik.http.routers.stremthru.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.stremthru.entrypoints: websecure
      traefik.http.routers.stremthru.service: stremthru
      traefik.http.routers.stremthru.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.stremthru-local-insecure.rule: Host(`stremthru.${LOCAL_DOMAIN}`)
      traefik.http.routers.stremthru-local-insecure.entrypoints: web
      traefik.http.routers.stremthru-local-insecure.service: stremthru
      traefik.http.routers.stremthru-local-insecure.middlewares: stremthru-web-redirect
      # Local domain secure
      traefik.http.routers.stremthru-local.rule: Host(`stremthru.${LOCAL_DOMAIN}`)
      traefik.http.routers.stremthru-local.entrypoints: websecure
      traefik.http.routers.stremthru-local.service: stremthru
      traefik.http.routers.stremthru-local.tls: true
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true
