version: '3.7'

services:
  aiostreams:
    image: ghcr.io/viren070/aiostreams:latest
    container_name: aiostreams
    restart: unless-stopped
    env_file:
      - ./app.env
    healthcheck:
      test: ["CMD-SHELL","wget -qO- http://localhost:3000/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - ${APP_DATA_DIR}/aiostreams:/app/data
    networks:
      - tipi_main_network
    labels:
      traefik.enable: "true"

      # Redirect HTTP → HTTPS
      traefik.http.middlewares.aiostreams-redirect.redirectscheme.scheme: https

      # Internal port
      traefik.http.services.aiostreams.loadbalancer.server.port: "3000"

      # HTTP router (insecure)
      traefik.http.routers.aiostreams-insecure.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.aiostreams-insecure.entrypoints: "web"
      traefik.http.routers.aiostreams-insecure.service: "aiostreams"
      traefik.http.routers.aiostreams-insecure.middlewares: "aiostreams-redirect"

      # HTTPS router (secure)
      traefik.http.routers.aiostreams.rule: "Host(`${APP_DOMAIN}`)"
      traefik.http.routers.aiostreams.entrypoints: "websecure"
      traefik.http.routers.aiostreams.service: "aiostreams"
      traefik.http.routers.aiostreams.tls.certresolver: "myresolver"

      # Local HTTP (insecure)
      traefik.http.routers.aiostreams-local-insecure.rule: "Host(`aiostreams.${LOCAL_DOMAIN}`)"
      traefik.http.routers.aiostreams-local-insecure.entrypoints: "web"
      traefik.http.routers.aiostreams-local-insecure.service: "aiostreams"
      traefik.http.routers.aiostreams-local-insecure.middlewares: "aiostreams-redirect"

      # Local HTTPS (secure)
      traefik.http.routers.aiostreams-local.rule: "Host(`aiostreams.${LOCAL_DOMAIN}`)"
      traefik.http.routers.aiostreams-local.entrypoints: "websecure"
      traefik.http.routers.aiostreams-local.service: "aiostreams"
      traefik.http.routers.aiostreams-local.tls: "true"

      # Managed by Runtipi
      runtipi.managed: "true"

networks:
  tipi_main_network:
    external: true
