services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: kopia-server
    restart: unless-stopped
    ports:
      - ${APP_PORT}:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_SERVER_USERNAME}
      - --server-password=${KOPIA_SERVER_PASSWORD}
    environment:
      - KOPIA_PASSWORD=${KOPIA_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - ${APP_DATA_DIR}/data/cache:/app/cache
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - ${APP_DATA_DIR}/data/repository:/repository
      - ${APP_DATA_DIR}/data/tmp:/tmp:shared
      - /:/data:ro
    networks:
      - tipi_main_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.kopia-web-redirect.redirectscheme.scheme: https
      traefik.http.services.kopia.loadbalancer.server.port: 51515
      # Web (insecure)
      traefik.http.routers.kopia-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kopia-insecure.entrypoints: web
      traefik.http.routers.kopia-insecure.service: kopia
      traefik.http.routers.kopia-insecure.middlewares: kopia-web-redirect
      # Websecure (public)
      traefik.http.routers.kopia.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kopia.entrypoints: websecure
      traefik.http.routers.kopia.service: kopia
      traefik.http.routers.kopia.tls.certresolver: myresolver
      # Local domain (insecure)
      traefik.http.routers.kopia-local-insecure.rule: Host(`kopia.${LOCAL_DOMAIN}`)
      traefik.http.routers.kopia-local-insecure.entrypoints: web
      traefik.http.routers.kopia-local-insecure.service: kopia
      traefik.http.routers.kopia-local-insecure.middlewares: kopia-web-redirect
      # Local domain (secure)
      traefik.http.routers.kopia-local.rule: Host(`kopia.${LOCAL_DOMAIN}`)
      traefik.http.routers.kopia-local.entrypoints: websecure
      traefik.http.routers.kopia-local.service: kopia
      traefik.http.routers.kopia-local.tls: true
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true
