services:
  kopia:
    image: kopia/kopia:latest
    container_name: kopia
    hostname: kopia-server
    restart: unless-stopped
    ports:
      - ${APP_PORT}:51515
    command:
      - server
      - start
      - --disable-csrf-token-checks
      - --insecure
      - --address=0.0.0.0:51515
      - --server-username=${KOPIA_SERVER_USERNAME}
      - --server-password=${KOPIA_SERVER_PASSWORD}
    environment:
      - KOPIA_PASSWORD=${KOPIA_PASSWORD}
    volumes:
      - ${APP_DATA_DIR}/data/config:/app/config
      - ${APP_DATA_DIR}/data/cache:/app/cache
      - ${APP_DATA_DIR}/data/logs:/app/logs
      - ${APP_DATA_DIR}/data/repository:/repository
      - ${APP_DATA_DIR}/data/tmp:/tmp:shared
      - /:/data:ro
    networks:
      - tipi_main_network
    logging:
      driver: json-file
      options:
        max-size: 10m
        max-file: "3"
    labels:
      # Traefik configuration
      traefik.enable: true
      traefik.http.services.kopia.loadbalancer.server.port: 51515
      
      # HTTP to HTTPS redirect
      traefik.http.middlewares.kopia-redirect.redirectscheme.scheme: https
      
      # Main domain routing
      traefik.http.routers.kopia-web.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kopia-web.entrypoints: web
      traefik.http.routers.kopia-web.middlewares: kopia-redirect
      
      traefik.http.routers.kopia-websecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.kopia-websecure.entrypoints: websecure
      traefik.http.routers.kopia-websecure.tls.certresolver: myresolver
      
      # Local domain routing
      traefik.http.routers.kopia-local.rule: Host(`kopia.${LOCAL_DOMAIN}`)
      traefik.http.routers.kopia-local.entrypoints: web
      traefik.http.routers.kopia-local.middlewares: kopia-redirect
      
      traefik.http.routers.kopia-local-secure.rule: Host(`kopia.${LOCAL_DOMAIN}`)
      traefik.http.routers.kopia-local-secure.entrypoints: websecure
      traefik.http.routers.kopia-local-secure.tls: true
      
      runtipi.managed: true

networks:
  tipi_main_network:
    external: true
