services:
  netbird:
    container_name: netbird
    image: netbirdio/netbird:latest
    environment:
      - NB_SETUP_KEY=${NB_SETUP_KEY}
      - NB_LOG_LEVEL=${NB_LOG_LEVEL-info}
      - NB_DNS_RESOLVER_ADDRESS=${NB_DNS_RESOLVER_ADDRESS-}
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
      - SYS_RESOURCE
    network_mode: host
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data:/etc/netbird
    labels:
      runtipi.managed: true
