version: '3.7'

services:
  torbox-media-center:
    image: anonymoussystems/torbox-media-center:main
    container_name: torbox-media-center
    stdin_open: true
    tty: true
    restart: unless-stopped
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-Europe/Prague}
      - TORBOX_API_KEY=${TORBOX_API_KEY}
      - MOUNT_METHOD=${MOUNT_METHOD:-strm}
      - MOUNT_PATH=${MOUNT_PATH:-/torbox}
    volumes:
      - ${APP_DATA_DIR}/data/torbox-data:/torbox
    networks:
      - tipi_main_network
    labels:
      runtipi.managed: "true"
      com.centurylinklabs.watchtower.enable: "false"

networks:
  tipi_main_network:
    external: true
