version: "3.7"

services:
  gitea:
    image: gitea/gitea:1.23.7
    container_name: gitea
    environment:
      - USER_UID=1000
      - USER_GID=1000
      # SQLite configuration
      - GITEA__database__DB_TYPE=sqlite3
      - GITEA__database__PATH=/data/gitea/gitea.db
      # Other important settings
      - GITEA__server__HTTP_PORT=3000
      - GITEA__server__ROOT_URL=http://${APP_DOMAIN}:${APP_PORT}/
      - GITEA__server__DOMAIN=${APP_DOMAIN}
    restart: unless-stopped
    volumes:
      - ${APP_DATA_DIR}/data/gitea:/data
    ports:
      - ${APP_PORT}:3000
      - "222:22"
    networks:
      - tipi_main_network
    labels:
      # Main
      traefik.enable: true
      traefik.http.middlewares.gitea-web-redirect.redirectscheme.scheme: https
      traefik.http.services.gitea.loadbalancer.server.port: 3000
      # Web
      traefik.http.routers.gitea-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gitea-insecure.entrypoints: web
      traefik.http.routers.gitea-insecure.service: gitea
      traefik.http.routers.gitea-insecure.middlewares: gitea-web-redirect
      # Websecure
      traefik.http.routers.gitea.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.gitea.entrypoints: websecure
      traefik.http.routers.gitea.service: gitea
      traefik.http.routers.gitea.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.gitea-local-insecure.rule: Host(`gitea.${LOCAL_DOMAIN}`)
      traefik.http.routers.gitea-local-insecure.entrypoints: web
      traefik.http.routers.gitea-local-insecure.service: gitea
      traefik.http.routers.gitea-local-insecure.middlewares: gitea-web-redirect
      # Local domain secure
      traefik.http.routers.gitea-local.rule: Host(`gitea.${LOCAL_DOMAIN}`)
      traefik.http.routers.gitea-local.entrypoints: websecure
      traefik.http.routers.gitea-local.service: gitea
      traefik.http.routers.gitea-local.tls: true
      runtipi.managed: true
